services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    labels:
      - com.github.nginx-proxy.nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    networks:
      - proxy-network

  letsencrypt:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-letsencrypt
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    environment:
      - DEFAULT_EMAIL=${ADMIN_EMAIL}
      - NGINX_PROXY_CONTAINER=nginx-proxy
    networks:
      - proxy-network

  db-postgres:
    image: postgres:16
    ports:
      - '5432:5432'
    container_name: ${POSTGRES_HOST}
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - shortic-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_DATABASE}", "-U", "${POSTGRES_USERNAME}" ]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  fast-postgres:
    image: postgres:16
    ports:
      - '5433:5432'
    container_name: ${FAST_POSTGRES_HOST}
    restart: always
    environment:
      - POSTGRES_USER=${FAST_POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${FAST_POSTGRES_PASSWORD}
      - POSTGRES_DB=${FAST_POSTGRES_DATABASE}
    volumes:
      - shortic-fast-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${FAST_POSTGRES_DATABASE}", "-U", "${FAST_POSTGRES_USERNAME}" ]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  redis:
    image: redis:7.2-rc-alpine
    restart: always
    container_name: ${REDIS_HOST}
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - shortic-cache:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  config-server:
    image: shortic-config
    ports:
      - '${CONFIG_PORT}:${CONFIG_PORT}'
    build:
      context: .
      dockerfile: Dockerfile-config-service
    container_name: shortic-config-server
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${CONFIG_PORT}/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app-network

  discovery-service:
    image: shortic-eureka
    ports:
      - '${EUREKA_PORT}:${EUREKA_PORT}'
    build:
      context: .
      dockerfile: Dockerfile-discovery-service
    container_name: shortic-eureka-server
    restart: always
    depends_on:
      config-server:
        condition: service_healthy
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${EUREKA_PORT}/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app-network

  backend-giving-service:
    image: shortic-backend-giving
    ports:
      - '${GIVING_SERVICE_PORT}:${GIVING_SERVICE_PORT}'
    build:
      context: .
      dockerfile: Dockerfile-backend-giving-service
    container_name: backend-giving-service
    restart: always
    depends_on:
      discovery-service:
        condition: service_healthy
      fast-postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${GIVING_SERVICE_PORT}/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - app-network

  backend-counting-service:
    image: shortic-backend-counting
    ports:
      - '${COUNTING_SERVICE_PORT}:${COUNTING_SERVICE_PORT}'
    build:
      context: .
      dockerfile: Dockerfile-backend-counting-service
    container_name: backend-counting-service
    restart: always
    depends_on:
      db-postgres:
        condition: service_healthy
      backend-giving-service:
        condition: service_healthy
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${COUNTING_SERVICE_PORT}/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - app-network

  frontend:
    image: shortic-frontend
    build:
      context: .
      dockerfile: Dockerfile-frontend-service
    container_name: shortic-frontend
    restart: always
    depends_on:
      backend-counting-service:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=${DOMAIN_ADDRESS}
      - LETSENCRYPT_HOST=${DOMAIN_ADDRESS}
      - LETSENCRYPT_EMAIL=${ADMIN_EMAIL}
    networks:
      - proxy-network
      - app-network

volumes:
  shortic-cache:
    driver: local
  shortic-db-data:
    driver: local
  shortic-fast-data:
    driver: local

networks:
  proxy-network:
  app-network: