FROM maven:3.8.4-openjdk-17 AS builder
WORKDIR /app
COPY config-service /app/.
COPY .env /app/.env
RUN mvn -f /app/pom.xml clean package -Dmaven.test.skip=true

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=builder /app/target/*.jar /app/*.jar
RUN apk add --no-cache curl
EXPOSE ${CONFIG_PORT}
ENTRYPOINT ["java", "-jar", "/app/*.jar"]
