FROM maven:3.8.4-openjdk-17 AS builder
WORKDIR /app
COPY discovery-service /app/.
RUN mvn -f /app/pom.xml clean package -Dmaven.test.skip=true

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=builder /app/target/*.jar /app/*.jar
RUN apk add --no-cache curl
EXPOSE ${EUREKA_PORT}
ENTRYPOINT ["java", "-jar", "/app/*.jar"]
