FROM maven:3.8.4-openjdk-17 AS builder
WORKDIR /app
COPY ./frontend-service/. /app/.
# просто внедрить зависимость в локальный репозиторий - не работает, надо копировать классы
COPY ./common-storage/src/main/java/. /app/src/main/java/.
COPY ./common-storage/. /common-storage/.
RUN mvn -f /common-storage/pom.xml clean install -Dmaven.test.skip=true
RUN mvn -f /app/pom.xml clean package -Dmaven.test.skip=true

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=builder /app/target/*.jar /app/*.jar
# возможно лишнее, т.к. в конфиг сервисе уже указано
ENV SERVER_PORT=${FRONTEND_SERVICE_PORT}
ENTRYPOINT ["java", "-jar", "/app/*.jar"]