version: '3.3'

services:

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    container_name: shortic-mongo-db
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - shortic-mongo:/data/db
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 1s
      timeout: 5s
      retries: 10

  db-postgres:
    image: postgres:12-alpine
    ports:
      - '15434:15432'
    container_name: shortic-db-postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - shortic-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "user" ]
      interval: 1s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7.2-rc-alpine
    restart: always
    container_name: shortic-db-redis
    ports:
      - '16379:16379'
    command: redis-server --save 20 1 --loglevel warning --requirepass parole
    volumes:
      - shortic-cache:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "parole", "ping"]
      interval: 1s
      timeout: 5s
      retries: 10

  config-server:
    image: shortic-config
    ports:
      - '18001:18001'
    build:
      context: ./config-service
      dockerfile: Dockerfile
    container_name: shortic-config-server
    restart: always
    healthcheck:
      # TODO работает? самописная проверка. если нет ответа, то вернёт статус 1 - значит unhealthy
      test: curl --fail http://localhost:18001/actuator || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  eureka:
    image: shortic-eureka
    ports:
      - '18761:18761'
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    container_name: shortic-eureka-server
    restart: always
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      - SERVER_PORT=18761
      - SPRING_CLOUD_CONFIG_URI=http://shortic-config-server:18001
    healthcheck:
      # TODO работает? самописная проверка. если нет ответа, то вернёт статус 1 - значит unhealthy
      test: curl --fail http://localhost:18761/eureka/apps || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  backend-counting-service:
    image: shortic-backend-counting
    ports:
      - '18082:18082'
    build:
      context: ./backend-counting-service
      dockerfile: Dockerfile
    container_name: backend-counting-service
    restart: always
    depends_on:
      eureka:
        condition: service_healthy
      db-postgres:
        condition: service_healthy
    environment:
      - SERVER_PORT=18082
      - SPRING_DATASOURCE_URL=jdbc:postgresql://shortic-db-postgres/postgres
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:18761/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://shortic-config-server:18001

  backend-giving-service:
    image: shortic-backend-giving
    ports:
      - '18081:18081'
    build:
      context: ./backend-giving-service
      dockerfile: Dockerfile
    container_name: backend-giving-service
    restart: always
    depends_on:
      eureka:
        condition: service_healthy
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - SERVER_PORT=18081
      - SPRING_DATA_MONGODB_HOST=shortic-mongo-db
      - SPRING_DATA_REDIS_HOST=shortic-db-redis
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:18761/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://shortic-config-server:18001

  frontend:
    image: shortic-frontend
    ports:
      - '18080:18080'
    build:
      context: ./frontend-service
      dockerfile: Dockerfile
    container_name: shortic-frontend
    depends_on:
      backend-counting-service:
        condition: service_started
      backend-giving-service:
        condition: service_started
    environment:
      - SERVER_PORT=18080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:18761/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://shortic-config-server:18001

volumes:
  shortic-cache:
    driver: local
  shortic-mongo:
    driver: local
  shortic-db-data:
    driver: local