server:
  port: 18081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:18761/eureka
#properties:
#  adultAgeCriteria: 16

spring:
  application:
    name: backend_giving
  cache:
    type: redis
    cache-names: redis-cache
#  data:
#    redis:
#      host: localhost
#      port: 16379
#      password: parole
#    mongodb:
#      host: localhost
#      port: 27017
#      database: giving_db
#      username: user
#      password: password
  datasource:
    url: jdbc:h2:file:./dev_data/giving_db
    username: sa
    password:
logging:
  level:
    org.springframework: INFO
    org.pablos.backend: DEBUG
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 5
  file:
    name: ./logs/${spring.application.name}.log