server:
  port: 18082
properties:
  api_key: ${YANDEX_API_KEY}
  threads_number: ${NUMBER_OF_THREADS_FOR_SCHEDULED_CHECKING}
  checking_length: ${TIME_LIMIT_FOR_SCHEDULED_CHECKING_IN_MINUTES}

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: backend_counting
  datasource:
    url: jdbc:h2:file:./dev_data/counting_db
    username: sa
    password:
#      TODO менять
#    datasource:
#      url: jdbc:postgresql://localhost:15432/${POSTGRES_DATABASE}
#      username: ${POSTGRES_USERNAME}
#      password: ${POSTGRES_PASSWORD}
#      driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    default-schema: shortic
    change-log: classpath:db/changelog/changelog-master.xml
    contexts: development, production
    drop-first: false