server:
  port: ${GIVING_SERVICE_PORT}
spring:
  config:
    import: optional:file:.env[.properties]
  cache:
    type: redis
    cache-names: ${REDIS_HOST}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      password: ${REDIS_PASSWORD}
      port: 6379
  datasource:
    url: jdbc:postgresql://${FAST_POSTGRES_HOST:localhost}:5432/${FAST_POSTGRES_DATABASE}
    username: ${FAST_POSTGRES_USERNAME}
    password: ${FAST_POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    default-schema: fast
    change-log: classpath:db/changelog/changelog-master.xml
    contexts: development, production
    drop-first: false
