server:
  port: 18081

spring:
  config:
    import: optional:file:.env[.properties]
  cache:
    type: redis
    cache-names: shortic-db-redis
  data:
    redis:
      # for launch from IDEA
      #host: localhost
      host: shortic-db-redis
#      host: ${REDIS_HOST:localhost}
      port: 6379
#      database: 0
#      username: shortic
      password: mcjbd7eD
#      password: ${REDIS_PASSWORD}
  datasource:
    # for launch from IDEA
    #url: jdbc:postgresql://localhost:5433/fast_db
    url: jdbc:postgresql://fast-postgres:5432/fast_db
    username: fast_user
    password: Sujfrbe
    #    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5433/${POSTGRES_DATABASE:fast_db}
    #    username: ${POSTGRES_USERNAME:fast_user}
    #    password: ${POSTGRES_PASSWORD:Sujfrbe}
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    default-schema: fast
    change-log: classpath:db/changelog/changelog-master.xml
    contexts: development, production
    drop-first: false
