server:
  port: ${FRONTEND_SERVICE_PORT}
properties:
  from_who: ${OFFER_FROM_WHO}
spring:
  config:
    import: optional:file:.env[.properties]
  mvc:
    hiddenmethod:
      filter:
        enabled: true