server:
  port: 18080
properties:
  from_who: vasya
#  TODO from_who: ${OFFER_FROM_WHO}
spring:
  config:
    import: optional:file:.env[.properties]
  mvc:
    hiddenmethod:
      filter:
        enabled: true