spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/services
  security:
    user:
      password: parole

server:
  port: 18001